# Generated by Django 6.0.5 on 2026-05-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('appliance', models.CharField(max_length=100)),
                ('timeline', models.CharField(max_length=50)),
                ('selected_plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
